# Generated by Django 5.2.8 on 2025-11-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='renual_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
