# Generated by Django 5.2.8 on 2025-11-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_book_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookissue',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
