# Generated by Django 5.2.8 on 2025-11-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bookissue_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
