# Generated by Django 5.2.8 on 2025-11-11 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_bookissue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookissue',
            name='slug',
        ),
    ]
